export const API_URLS = {
  login: "https://heliverse-assignment-backend-w4m5.onrender.com/api/users/login",
  getUniqueLocationsByRole: "https://heliverse-assignment-backend-w4m5.onrender.com/api/users/get-loc",
  getOrdersByFilters: "https://heliverse-assignment-backend-w4m5.onrender.com/api/orders/filter",
  updateOrdersStatusAndDeliveryStatus: "https://heliverse-assignment-backend-w4m5.onrender.com/api/orders/status",
  getUsersByLocationAndRole: "https://heliverse-assignment-backend-w4m5.onrender.com/api/users/get-userByLocationRole",
  addPatient: "https://heliverse-assignment-backend-w4m5.onrender.com/api/patient/create-patient",
  getPatients: "https://heliverse-assignment-backend-w4m5.onrender.com/api/patient/get-patients",
  addOrUpdateMeals: "https://heliverse-assignment-backend-w4m5.onrender.com/api/menu",
  getMealsByPatient: "https://heliverse-assignment-backend-w4m5.onrender.com/api/menu",
  getPatientsWithMeal: "https://heliverse-assignment-backend-w4m5.onrender.com/api/menu/get-pids",
  orderFood: "https://heliverse-assignment-backend-w4m5.onrender.com/api/orders/orders",
  addPantry: "https://heliverse-assignment-backend-w4m5.onrender.com/api/users/register",
  getPantry: "https://heliverse-assignment-backend-w4m5.onrender.com/api/staff/get-pantry",
  getDelivery: "https://heliverse-assignment-backend-w4m5.onrender.com/api/staffd/get-delivery",
  addMenuItem: "https://heliverse-assignment-backend-w4m5.onrender.com/api/menu/add",
  getMenu: "https://heliverse-assignment-backend-w4m5.onrender.com/api/menu",
  updateMealStatus: "https://heliverse-assignment-backend-w4m5.onrender.com/api/meals/update",
  getMealStatus: "https://heliverse-assignment-backend-w4m5.onrender.com/api/meals",
};
